const API_URL = process.env.API_URL

export const LOGIN_URL = API_URL + "/login"

export const DASHBOARD_DATA_URL = API_URL + "/dashboard-data"
export const RESET_PASSWORD_URL = API_URL + "/reset"
export const UNIVERSITY_URL = API_URL + "/universities"
export const STUDIES_URL = API_URL + "/studies"
export const STUDY_NAME_URL = API_URL + "/study-names"
export const STUDY_YEARS_URL = API_URL + "/study-years"
export const COMBO_DATA_URL = API_URL + "/combo-data?model="
export const USER_URL = API_URL + "/users"
export const SUPERVISOR_URL = API_URL + "/supervisors"
export const ADD_MARKETING_URL = API_URL + "/supervisor/attach-marketing"
export const DETACH_MARKETING_URL = API_URL + "/supervisor/detach-marketing"
export const SEARCH_MARKETING_URL = API_URL + "/supervisor/search-marketing"
export const MARKETING_URL = API_URL + "/marketings"
export const MARKETING_ACTION_URL = API_URL + "/marketing-actions"
export const PRODUCT_URL = API_URL + "/products"
export const ROLE_URL = API_URL + "/roles"
export const ROLE_PERMISSIONS_URL = API_URL + "/role/permissions"
export const PERMISSION_URL = API_URL + "/permissions"
export const SCHEDULLE_URL = API_URL + "/schedulles"
export const ME_URL = API_URL + "/me"
export const PROFILE_URL = API_URL + "/profile"
export const MARKETING_REPORTS_URL = API_URL + "/marketing-reports"
export const ATTACHMENTS_URL = API_URL + "/attachments"
export const DATA_EXPORT_URL = API_URL + "/export-data"
export const ACTIVITIES_URL = API_URL + "/activities"
export const CONTACT_URL = API_URL + "/contacts"
export const TARGET_YEARS = API_URL + "/target-years"
export const TARGET_URL = API_URL + "/marketing-targets"
export const CHECK_TARGET_CODE_URL = API_URL + "/check-target-code"
export const DP_URL = API_URL + "/down-payments"
export const STORE_DP_URL = API_URL + "/post-down-payment"
